// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for artist documents */
interface ArtistDocumentData {
    /**
     * full name field in *artist*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: artist.fname
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    fname: prismicT.KeyTextField;
    /**
     * year of birth field in *artist*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: artist.year_of_birth
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    year_of_birth: prismicT.NumberField;
    /**
     * year of death field in *artist*
     *
     * - **Field Type**: Number
     * - **Placeholder**: this one is optional (of course)
     * - **API ID Path**: artist.year_of_death
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    year_of_death: prismicT.NumberField;
    /**
     * documents field in *artist*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: artist.documents[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    documents: prismicT.GroupField<Simplify<ArtistDocumentDataDocumentsItem>>;
}
/**
 * Item in artist → documents
 *
 */
export interface ArtistDocumentDataDocumentsItem {
    /**
     * document field in *artist → documents*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: artist.documents[].document
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    document: prismicT.RelationField<"document">;
}
/**
 * artist document from Prismic
 *
 * - **API ID**: `artist`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArtistDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ArtistDocumentData>, "artist", Lang>;
/** Content for document documents */
interface DocumentDocumentData {
    /**
     * title field in *document*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: document.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * type field in *document*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: viðtal
     * - **API ID Path**: document.type
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    type: prismicT.SelectField<"viðtal" | "eigin skrif" | "erindi og ræður" | "fyrirlestrar" | "gagnrýni og umfjallanir" | "heimildarmyndir" | "kvikmyndir" | "myndbandsviðtöl" | "samtöl" | "sýningarskrár" | "útvarps- og hlaðvarpsviðtöl", "filled">;
    /**
     * date field in *document*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: document.date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    date: prismicT.DateField;
    /**
     * origin label field in *document*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: document.origin_label
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    origin_label: prismicT.KeyTextField;
    /**
     * origin link field in *document*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: document.origin_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    origin_link: prismicT.LinkField;
}
/**
 * document document from Prismic
 *
 * - **API ID**: `document`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DocumentDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<DocumentDocumentData>, "document", Lang>;
/** Content for homepage documents */
interface HomepageDocumentData {
    /**
     * title field in *homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * seo title field in *homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.seo_title
     * - **Tab**: seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_title: prismicT.KeyTextField;
    /**
     * seo description field in *homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.seo_description
     * - **Tab**: seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_description: prismicT.KeyTextField;
    /**
     * seo image field in *homepage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.seo_image
     * - **Tab**: seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    seo_image: prismicT.ImageField<never>;
}
/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for interview documents */
type InterviewDocumentData = Record<string, never>;
/**
 * interview document from Prismic
 *
 * - **API ID**: `interview`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InterviewDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<InterviewDocumentData>, "interview", Lang>;
/** Content for site settings documents */
interface SiteSettingsDocumentData {
    /**
     * site name field in *site settings*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: site_settings.site_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    site_name: prismicT.KeyTextField;
    /**
     * about field in *site settings*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: site_settings.about
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    about: prismicT.RichTextField;
}
/**
 * site settings document from Prismic
 *
 * - **API ID**: `site_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteSettingsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<SiteSettingsDocumentData>, "site_settings", Lang>;
export type AllDocumentTypes = ArtistDocument | DocumentDocument | HomepageDocument | InterviewDocument | SiteSettingsDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ArtistDocumentData, ArtistDocumentDataDocumentsItem, ArtistDocument, DocumentDocumentData, DocumentDocument, HomepageDocumentData, HomepageDocument, InterviewDocumentData, InterviewDocument, SiteSettingsDocumentData, SiteSettingsDocument, AllDocumentTypes };
    }
}
